version: '3.8'

services:
  # ================================================================
  # INFLUXDB - Time Series Database
  # ================================================================
  influxdb:
    image: influxdb:2.7
    container_name: trading_influxdb
    ports:
      - "8086:8086"
    environment:
      # Initial setup
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=trading-org
      - DOCKER_INFLUXDB_INIT_BUCKET=stock-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-super-secret-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ================================================================
  # GRAFANA - Visualization & Dashboards
  # ================================================================
  grafana:
    image: grafana/grafana:10.2.0
    container_name: trading_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - trading-network
    depends_on:
      - influxdb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# ================================================================
# NETWORKS
# ================================================================
networks:
  trading-network:
    driver: bridge
    name: trading-network

# ================================================================
# VOLUMES
# ================================================================
volumes:
  influxdb-data:
    name: trading_influxdb_data
  influxdb-config:
    name: trading_influxdb_config
  grafana-data:
    name: trading_grafana_data
